messages:
  - name:        "Internal Error"
    code:        1
    level:       Error
    description: "There was an internal error in the toolchain. This is almost always a bug in the implementation."
    template:    "Internal error: %v"
    args:
      - name: detail
        type: string

  - name:        "Not Yet Implemented"
    code:        2
    level:       Error
    description: "A feature that the configuration is depending on is not implemented yet."
    template:    "Not yet implemented: %s"
    args:
      - name: detail
        type: string

  - name:        "Parse Error"
    code:        3
    level:       Warning
    description: "There was a parse error during the parsing of the configuration text"
    template:    "Parse error: %s"
    args:
      - name: detail
        type: string

  - name:        "Deprecated"
    code:        4
    level:       Warning
    description: "A feature that the configuration is depending on is now deprecated."
    template:    "Deprecated: %s"
    args:
      - name: detail
        type: string

  - name:        "Gateway Not Found"
    code:        20
    level:       Error
    description: "The Gateway resource that the Virtual Service is referencing does not exist."
    template:    "Referenced Gateway not found: %q"
    args:
      - name: gateway
        type: string
